### ISSUE TITLE
Gather descriptions of experimental studies in this meta analysis

### ISSUE THREAD

**Issue by emmastrand** [Resilience-Biomarkers-for-Aquaculture/Cvirg_Pmarinus_RNAseq#3]
As the rnaseq pipelines finish, it would be good to outline/get on the same page regarding exactly what comparisons we want to do with the output of these pipelines. 

**To-Do list for this:** 

- [x] download metadata for samples (tissue type, exposure, timepoint, species, etc.)
- [x] Come up with game plan for this comparison -- might be better for next meeting.

**Comment by shellywanamaker** [comment]
meta data is already linked here:https://resilience-biomarkers-for-aquaculture.github.io/about/#omics-datasets-processed

**Comment by shellywanamaker** [comment]
the info is sometimes in last columns
